upApp: add more packages

diff --git a/app-core/ugs/files/sbin/upApp b/app-core/ugs/files/sbin/upApp
--- a/app-core/ugs/files/sbin/upApp
+++ b/app-core/ugs/files/sbin/upApp
@@ -10,6 +10,8 @@ DEBUG_LOG="${TMP_DIR}/${PROGNAME}-debug.log"
 ERROR_LOG="${TMP_DIR}/${PROGNAME}-error.log"
 JSON_LOG="${TMP_DIR}/${PROGNAME}-json.log"
 
+rm -rf "${TMP_DIR}"
+
 mkdir -p "$TMP_DIR"
 : > "$ERROR_LOG"
 : > "$JSON_LOG"
@@ -244,6 +246,29 @@ update_git_package() {
 	fi
 }
 
+scrape_gnupg_versions() {
+	local gnupg_url="https://www.gnupg.org/download/index.html"
+
+	echo "Scraping GnuPG download page..." >> "$DEBUG_LOG"
+
+	local gnupg_version=$(curl -s "$gnupg_url" | grep -A6 '<tr>' | grep -A6 'GnuPG<' | grep -v '(devel)' | grep -Eo '<td class="left">[^<]+</td>' | sed -E 's/<[^>]+>//g' | grep -E '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
+	if [[ -z "$gnupg_version" ]]; then
+		echo "Failed to fetch GnuPG version" >> "$ERROR_LOG"
+		return 1
+	fi
+	echo "Fetched GnuPG version: $gnupg_version" >> "$DEBUG_LOG"
+
+	local libgpg_error_version=$(curl -s "$gnupg_url" | grep -A6 '<tr>' | grep -A6 'Libgpg-error' | grep -Eo '<td class="left">[^<]+</td>' | sed -E 's/<[^>]+>//g' | head -n 2 | tail -n 1)
+	if [[ -z "$libgpg_error_version" ]]; then
+		echo "Failed to fetch libgpg-error version" >> "$ERROR_LOG"
+		return 1
+	fi
+	echo "Fetched libgpg-error version: $libgpg_error_version" >> "$DEBUG_LOG"
+
+	update_ebuild "app-crypto/gnupg" "gnupg" "$gnupg_version"
+	update_ebuild "lib-core/libgpg-error" "libgpg-error" "$libgpg_error_version"
+}
+
 cryptsetup_version=$(fetch_latest_cryptsetup_version)
 [[ $? -eq 0 ]] && update_ebuild "app-fs/cryptsetup" "cryptsetup" "$cryptsetup_version"
 
@@ -256,7 +281,326 @@ if [[ $? -eq 0 ]]; then
 	update_gnu_package "bison"
 	update_gnu_package "make"
 	update_gnu_package "texinfo"
+	update_gnu_package "ed"
+	update_gnu_package "groff"
+	update_gnu_package "help2man"
 fi
+
+#!/bin/bash
+
+REPO_PATH="/var/db/repos/bp"
+
+PROGNAME="upApp"
+
+TMP_DIR="/tmp/${PROGNAME}"
+
+DEBUG_LOG="${TMP_DIR}/${PROGNAME}-debug.log"
+ERROR_LOG="${TMP_DIR}/${PROGNAME}-error.log"
+JSON_LOG="${TMP_DIR}/${PROGNAME}-json.log"
+
+rm -rf "${TMP_DIR}"
+
+mkdir -p "$TMP_DIR"
+: > "$ERROR_LOG"
+: > "$JSON_LOG"
+: > "$DEBUG_LOG"
+
+handle_github() {
+	local repo_url="$1"
+	local repo_slug=$(echo "$repo_url" | sed -E 's|https?://github\.com/([^/]+/[^/]+).*|\1|')
+	local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
+
+	echo "repo_slug $repo_slug" >> "$DEBUG_LOG"
+	echo "urlencode $encoded_slug" >> "$DEBUG_LOG"
+
+	local releases_api_url="https://api.github.com/repos/$repo_slug/releases/latest"
+	local tags_api_url="https://api.github.com/repos/$repo_slug/tags"
+	local auth_header="Authorization: token $GITHUB_TOKEN"
+	echo "auth_header $auth_header" >> "$DEBUG_LOG"
+
+	local latest_release_info=$(curl -s -H "$auth_header" "$releases_api_url")
+	local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
+	echo "api_url $releases_api_url" >> "$DEBUG_LOG"
+	echo "latest_release_info $latest_release_info" >> "$JSON_LOG"
+	echo "latest_version $latest_version" >> "$DEBUG_LOG"
+
+	if [[ -z "$latest_version" || "$latest_version" == "null" ]]; then
+		echo "No valid release found, checking tags..." >> "$DEBUG_LOG"
+		local latest_tag_info=$(curl -s -H "$auth_header" "$tags_api_url" | jq -r '.[0].name')
+		echo "api_url $tags_api_url" >> "$DEBUG_LOG"
+		echo "latest_tag_info $latest_tag_info" >> "$JSON_LOG"
+
+		if [[ -z "$latest_tag_info" || "$latest_tag_info" == "null" ]]; then
+			echo "Failed to fetch latest tag info" >> "$ERROR_LOG"
+			return 1
+		else
+			latest_version="$latest_tag_info"
+		fi
+	fi
+
+	# Remove v or V prefix if present
+	latest_version="${latest_version#[vV]}"
+
+	latest_version="${latest_version//_/\.}"
+	latest_version=$(echo "$latest_version" | sed -E "s/^.*-([0-9]+(\.[0-9]+)*).*/\1/")
+
+	echo "Successfully fetched version info: $latest_version" >> "$DEBUG_LOG"
+	echo "$latest_version"
+	return 0
+}
+
+handle_gitlab() {
+	local repo_url="$1"
+	local repo_slug=$(echo "$repo_url" | sed -E 's|https?://gitlab\.com/([^/]+/[^/]+).*|\1|')
+	local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
+	local api_url="https://gitlab.com/api/v4/projects/$encoded_slug/releases"
+	local auth_header="Authorization: Bearer $GITLAB_TOKEN"
+	local latest_release_info=$(curl -s -H "$auth_header" "$api_url" | jq '[.[] | select(.released_at)] | max_by(.released_at)')
+	if [[ $? -ne 0 || -z "$latest_release_info" ]]; then
+		echo "Failed to fetch latest release info"
+		return 1
+	else
+		local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
+		# Remove v or V prefix if present
+		latest_version="${latest_version#[vV]}"
+		echo "$latest_version"
+	fi
+}
+
+update_github_package() {
+	local category="$1"
+	local package_name="$2"
+	local repo_url="$3"
+	local latest_version=$(handle_github "$repo_url")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "${category}/${package_name}" "${package_name}" "${latest_version}"
+	else
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
+	fi
+}
+
+update_ebuild() {
+	local package_path="${REPO_PATH}/$1"
+	local package_name="$2"
+	local latest_version="$3"
+
+	local new_ebuild_filename="${package_name}-${latest_version}.ebuild"
+	local new_ebuild_file="${package_path}/${new_ebuild_filename}"
+
+	echo "Updating ebuild for package_path: $package_path, package_name: $package_name, latest_version: $latest_version" >> "$DEBUG_LOG"
+	echo "New ebuild filename: $new_ebuild_filename" >> "$DEBUG_LOG"
+	echo "New ebuild file path: $new_ebuild_file" >> "$DEBUG_LOG"
+
+	local ebuild_file=$(find "${package_path}" -type f -name "${package_name}-[0-9]*.ebuild" | sort -V | tail -n 1)
+	echo "Found ebuild file: $ebuild_file" >> "$DEBUG_LOG"
+
+	if [[ -z "$ebuild_file" ]]; then
+		echo "No existing ebuild file found for ${package_name} at ${package_path}." >> "$ERROR_LOG"
+		return 1
+	fi
+
+	local current_version=$(basename "$ebuild_file" | sed -e "s/^${package_name}-//" -e 's/\.ebuild$//')
+	echo "Current version: $current_version" >> "$DEBUG_LOG"
+
+	if [[ "$current_version" == "$latest_version" ]]; then
+		echo "No update needed for ${package_name} as it is already at the latest version: ${latest_version}." >> "$DEBUG_LOG"
+		return
+	fi
+
+	if [[ -f "$new_ebuild_file" ]]; then
+		echo "Ebuild file ${new_ebuild_filename} already exists. No update needed." >> "$DEBUG_LOG"
+		return
+	fi
+
+	mv "$ebuild_file" "$new_ebuild_file"
+	echo "New ebuild file created for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
+
+	if finalize_update "$package_path" "$package_name" "$new_ebuild_filename" "$latest_version"; then
+		echo "Ebuild successfully updated for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
+	else
+		echo "Failed to update ebuild for ${package_name}" >> "$ERROR_LOG"
+		return 1
+	fi
+}
+
+update_gitlab_package() {
+	local category="$1"
+	local package_name="$2"
+	local repo_url="$3"
+	local latest_version=$(handle_gitlab "$repo_url")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "${category}/${package_name}" "$package_name" "$latest_version"
+	else
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
+	fi
+}
+
+finalize_update() {
+	local package_path="$1"
+	local package_name="$2"
+	local new_ebuild_filename="$3"
+	local version="$4"
+
+	echo "Finalizing update for $package_name in $package_path" >> "$DEBUG_LOG"
+
+	if ! (cd "$package_path" && pkgdev manifest); then
+		echo "Error generating manifest for ${package_name}. Skipping..." >> "$ERROR_LOG"
+		return 1
+	fi
+
+	(cd "$package_path" && \
+			git add --all . && \
+			git -c user.name="${BOT_USER}" \
+			-c user.email="${BOT_EMAIL}" \
+			-c commit.gpgsign=true \
+			-c user.signingkey="${BOT_KEYID}" \
+			commit -m "Update ${package_name} to ${version}" && \
+		git push origin HEAD)
+
+	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
+}
+
+fetch_latest_gnu_version() {
+	local base_url="https://ftp.gnu.org/gnu/$1/"
+	local latest_version=$(curl -s "$base_url" | grep -oP 'href="\K'$1'-[0-9.]+(?=\.tar)' | \
+			sed 's/'$1'-//g' | \
+			sort -Vr | \
+		head -1)
+	if [[ -z "$latest_version" ]]; then
+		echo "Failed to fetch the latest $1 version" >> "$ERROR_LOG"
+		return 1
+	fi
+	echo "$latest_version"
+}
+
+fetch_latest_cryptsetup_version() {
+	local base_url="https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/"
+	local latest_version=$(curl -s "$base_url" | grep -oP 'href="v[0-9]+\.[0-9]+/' | grep -v -- "-rc" | sort -Vr | head -1 | cut -d '"' -f 2)
+
+	if [[ -z "$latest_version" ]]; then
+		echo "Failed to fetch the latest Cryptsetup version directory" >> "$ERROR_LOG"
+		return 1
+	fi
+
+	local version_page="${base_url}${latest_version}"
+	local latest_final_version=$(curl -s "$version_page" | grep -oP 'cryptsetup-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | sort -Vr | head -1)
+
+	if [[ -z "$latest_final_version" ]]; then
+		echo "Failed to find the latest Cryptsetup final version" >> "$ERROR_LOG"
+		return 1
+	fi
+
+	echo "$latest_final_version"
+}
+
+update_gnu_package() {
+	local cat=$1
+	local package_name=$2
+	local package_version=$(fetch_latest_gnu_version "$package_name")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "$cat/$package_name" "$package_name" "$package_version"
+	fi
+}
+
+fetch_latest_git_version() {
+	local repo_url="$1"
+	local current_version="$2"
+
+	local latest_version=$(git ls-remote --tags --sort="-v:refname" "$repo_url" \
+		| grep -oP 'refs/tags/(v?|libnetfilter_log-|libcap-|ulogd-|[a-zA-Z_-]+-)?\K[0-9]+\.[0-9]+(\.[0-9]+)?' \
+		| sort -Vr \
+		| head -1)
+
+	if [[ -z "$latest_version" ]]; then
+		echo "Failed to fetch the latest version from $repo_url" >> "$ERROR_LOG"
+		return 1
+	fi
+
+	if [[ -n "$current_version" ]]; then
+		if [[ "$(printf '%s\n' "$latest_version" "$current_version" | sort -V | head -n1)" == "$latest_version" ]]; then
+			echo "No update needed. Current version ($current_version) is up-to-date or newer." >> "$DEBUG_LOG"
+			return 1
+		fi
+	fi
+
+	echo "$latest_version"
+}
+
+update_git_package() {
+	local category="$1"
+	local package_name="$2"
+	local repo_url="$3"
+
+	local package_version=$(fetch_latest_git_version "$repo_url")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "${category}/${package_name}" "$package_name" "$package_version"
+	else
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
+	fi
+}
+
+scrape_version() {
+	local category_package="$1"
+	local repo_url="$2"
+	local package_name=$(basename "$category_package")
+
+	echo "Scraping version for $category_package from $repo_url..." >> "$DEBUG_LOG"
+
+	local html_content=$(curl -s "$repo_url")
+
+	local version=""
+	if [[ "$package_name" == "gnupg" ]]; then
+		version=$(echo "$html_content" | grep -A6 '<tr>' | grep -A6 'GnuPG<' | grep -v '(devel)' | grep -Eo '<td class="left">[^<]+</td>' | sed -E 's/<[^>]+>//g' | grep -E '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
+	elif [[ "$package_name" == "libgpg-error" ]]; then
+		version=$(echo "$html_content" | grep -A6 '<tr>' | grep -A6 'Libgpg-error' | grep -Eo '<td class="left">[^<]+</td>' | sed -E 's/<[^>]+>//g' | head -n 2 | tail -n 1)
+	else
+		version=$(echo "$html_content" | grep -Eo "${package_name}-[0-9]+\.[0-9]+\.[0-9]+" | sed "s/${package_name}-//g" | head -n 1)
+	fi
+
+	if [[ -z "$version" ]]; then
+		echo "Failed to fetch version for $category_package" >> "$ERROR_LOG"
+		return 1
+	fi
+
+	echo "Fetched version for $category_package: $version" >> "$DEBUG_LOG"
+
+	update_ebuild "$category_package" "$package_name" "$version"
+}
+
+cryptsetup_version=$(fetch_latest_cryptsetup_version)
+[[ $? -eq 0 ]] && update_ebuild "app-fs/cryptsetup" "cryptsetup" "$cryptsetup_version"
+
+if [[ $? -eq 0 ]]; then
+	update_gnu_package "app-build" "autoconf-archive"
+	update_gnu_package "app-build" "autoconf"
+	update_gnu_package "app-build" "automake"
+	update_gnu_package "app-build" "gettext"
+	update_gnu_package "app-build" "m4"
+	update_gnu_package "app-build" "bison"
+	update_gnu_package "app-build" "make"
+	update_gnu_package "app-build" "texinfo"
+	update_gnu_package "app-core" "ed"
+	update_gnu_package "app-core" "groff"
+	update_gnu_package "app-core" "help2man"
+	update_gnu_package "lib-core" "gdbm"
+fi
+
+update_git_package "app-net" "bluez" "https://git.kernel.org/pub/scm/bluetooth/bluez.git"
+update_git_package "lib-core" "elfutils" "https://sourceware.org/git/elfutils.git"
+update_git_package "app-core" "kbd" "https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git"
+update_git_package "lib-core" "libcap" "https://kernel.googlesource.com/pub/scm/libs/libcap/libcap"
+update_git_package "app-net" "iw" "https://kernel.googlesource.com/pub/scm/linux/kernel/git/jberg/iw"
+update_git_package "app-net" "ethtool" "https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/"
+
+update_git_package "lib-net" "libnetfilter_conntrack" "https://git.netfilter.org/libnetfilter_conntrack"
+update_git_package "lib-net" "libnfnetlink" "https://git.netfilter.org/libnfnetlink"
+update_git_package "lib-net" "libnftnl" "https://git.netfilter.org/libnftnl"
+update_git_package "lib-net" "libmnl" "https://git.netfilter.org/libmnl"
+update_git_package "lib-net" "libnetfilter_log" "https://git.netfilter.org/libnetfilter_log"
+update_git_package "app-net" "nftables" "https://git.netfilter.org/nftables"
+update_git_package "app-var" "ulogd" "https://git.netfilter.org/ulogd"
+update_git_package "app-net" "ipset" "https://git.netfilter.org/ipset"
+update_git_package "app-net" "iptables" "https://git.netfilter.org/iptables"
 
 #update_github_package "app-dev" "eglexternalplatform" "https://github.com/NVIDIA/eglexternalplatform"
 #update_github_package "app-fs" "lsscsi" "https://github.com/hreinecke/lsscsi"
@@ -270,7 +614,7 @@ fi
 #update_github_package "lib-dev" "icu" "https://github.com/unicode-org/icu"
 #update_github_package "lib-net" "c-ares" "https://github.com/c-ares/c-ares"
 #update_github_package "xgui-lib" "yajl" "https://github.com/lloyd/yajl"
-update_git_package "app-net" "bluez" "https://git.kernel.org/pub/scm/bluetooth/bluez.git"
+
 update_github_package "app-compression" "libzip" "https://github.com/nih-at/libzip"
 update_github_package "app-core" "gentoo-functions" "https://github.com/gentoo/gentoo-functions"
 update_github_package "app-core" "pkgcore" "https://github.com/pkgcore/pkgcore"
@@ -300,6 +644,7 @@ update_github_package "app-var" "push" "https://github.com/vaeth/push"
 update_github_package "app-var" "quoter" "https://github.com/vaeth/quoter"
 update_github_package "bin" "apktool" "https://github.com/iBotPeaches/Apktool"
 update_github_package "bin" "vscodium" "https://github.com/VSCodium/VSCodium"
+update_github_package "lib-core" "libcap-ng" "https://github.com/stevegrubb/libcap-ng"
 update_github_package "lib-core" "libpcre2" "https://github.com/PCRE2Project/pcre2"
 update_github_package "lib-core" "musl-fts" "https://github.com/void-linux/musl-fts"
 update_github_package "lib-core" "ncurses" "https://github.com/ThomasDickey/ncurses-snapshots"
@@ -326,4 +671,6 @@ update_github_package "xmedia-app" "pngquant" "https://github.com/kornelski/pngq
 update_github_package "xmedia-lib" "graphene" "https://github.com/ebassi/graphene"
 update_github_package "xmedia-lib" "libimagequant" "https://github.com/ImageOptim/libimagequant"
 
-rm -rf "${TMP_DIR}"
+scrape_version "app-crypto/gnupg" "https://www.gnupg.org/download/index.html"
+scrape_version "lib-core/libgpg-error" "https://www.gnupg.org/download/index.html"
+scrape_version "lib-core/libedit" "https://thrysoee.dk/editline/"
