add more python packages

diff --git a/app-core/ugscripts/files/sbin/eclass_import b/app-core/ugscripts/files/sbin/eclass_import
--- a/app-core/ugscripts/files/sbin/eclass_import
+++ b/app-core/ugscripts/files/sbin/eclass_import
@@ -1,48 +1,63 @@
 #!/bin/bash
 
+# Set to stop on error
+set -e
+
+# Define constants
 TEMPLOCATION="/tmp/eclass_import"
-mkdir -p "${TEMPLOCATION}"
-[ ! -d "${TEMPLOCATION}/gentoo" ] && git clone https://github.com/gentoo/gentoo.git "${TEMPLOCATION}/gentoo" --depth 1
-cp "${TEMPLOCATION}"/gentoo/eclass/{autotools,cargo,cmake,distutils-r1,estack,flag-o-matic,font,git-r3,gnuconfig,go-module,kernel-2,libtool,linux-info,linux-mod,meson,multibuild,multiprocessing,ninja-utils,perl-functions,perl-module,out-of-source-utils,prefix,python*,qmake-utils,sgml-catalog-r1,toolchain-funcs,unpacker,user-info,xdg,xdg-utils,wrapper}.eclass /var/db/repos/bp/eclass/
+REPO_URL="https://github.com/gentoo/gentoo.git"
+ECCLASS_DIR="/var/db/repos/bp/eclass"
+ECCLASS_LIST=(autotools cargo cmake distutils-r1 estack flag-o-matic font git-r3 gnuconfig go-module kernel-2 libtool linux-info linux-mod meson multibuild multiprocessing ninja-utils perl-functions perl-module out-of-source-utils prefix python* qmake-utils sgml-catalog-r1 toolchain-funcs unpacker user-info xdg xdg-utils wrapper)
 
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/dosym8/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/einstalldocs/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eapi8-dosym/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eqawarn/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eutils/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ multilib/d'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\ multilib//g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\ readme.gentoo-r1//g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\$(get_libdir)/lib/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-arch/app-compression/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-portage/app-port/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-text/app-tex/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-lang/app-lang/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-libs\/glib/lib-live\/glib/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util\/desktop-file-utils/xgui-misc\/desktop-file-utils/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util/app-dev/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-vcs\/git/app-core\/git/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/media-fonts\/encodings/fonts\/encodings/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/media-libs\/fontconfig/fonts\/fontconfig/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-apps/app-core/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel/app-build/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-libs/lib-core/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/libelf/lib-core\/elfutils/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/pkgconfig/app-dev\/pkgconf/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/x11-apps\/mkfontscale/xgui-live-app\/mkfontscale/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/x11-misc\/shared-mime-info/xgui-live-app\/shared-mime-info/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\${EPREFIX}\$\(qt5_get_libdir\)\/qt5\/bin/\/usr\/bin/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\$(get_abi_LDFLAGS)/\${LDFLAGS}/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/get_abi_CHOST/CHOST/g'
-find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-dev\/ninja/app-dev\/samurai/g'
+# Clone the Gentoo repository if not already present
+if [ ! -d "${TEMPLOCATION}/gentoo" ]; then
+    echo "Cloning Gentoo repository to ${TEMPLOCATION}/gentoo..."
+    git clone "${REPO_URL}" "${TEMPLOCATION}/gentoo" --depth 1
+fi
 
-sed -i 's/.*qt5\/bin.*/	echo\ \/usr\/bin/' /var/db/repos/bp/eclass/qmake-utils.eclass
+# Copy the required eclass files to the target directory
+echo "Copying eclass files to ${ECCLASS_DIR}..."
+mkdir -p "${ECCLASS_DIR}"
+for eclass in "${ECCLASS_LIST[@]}"; do
+    cp -v "${TEMPLOCATION}/gentoo/eclass/${eclass}.eclass" "${ECCLASS_DIR}" 2>/dev/null || echo "Skipping ${eclass}, file does not exist."
+done
 
-sed -i 's/var\/lib/var/' /var/db/repos/bp/eclass/meson.eclass
+# Perform find-and-replace operations
+echo "Performing modifications on eclass files..."
+find "${ECCLASS_DIR}" -type f -name '*.eclass' -print0 | xargs -0 sed -i'' \
+    -e '/dosym8/d' \
+    -e '/einstalldocs/d' \
+    -e '/inherit\ eapi8-dosym/d' \
+    -e '/inherit\ eqawarn/d' \
+    -e '/inherit\ eutils/d' \
+    -e '/inherit\ multilib/d' \
+    -e 's/\ multilib//g' \
+    -e 's/\ readme.gentoo-r1//g' \
+    -e 's/\$(get_libdir)/lib/g' \
+    -e 's/app-arch/app-compression/g' \
+    -e 's/app-portage/app-port/g' \
+    -e 's/app-text/app-tex/g' \
+    -e 's/dev-lang/app-lang/g' \
+    -e 's/dev-libs\/glib/lib-live\/glib/g' \
+    -e 's/dev-util\/desktop-file-utils/xgui-misc\/desktop-file-utils/g' \
+    -e 's/dev-util/app-dev/g' \
+    -e 's/dev-vcs\/git/app-core\/git/g' \
+    -e 's/media-fonts\/encodings/fonts\/encodings/g' \
+    -e 's/media-libs\/fontconfig/fonts\/fontconfig/g' \
+    -e 's/sys-apps/app-core/g' \
+    -e 's/sys-devel/app-build/g' \
+    -e 's/sys-libs/lib-core/g' \
+    -e 's/virtual\/libelf/lib-core\/elfutils/g' \
+    -e 's/virtual\/pkgconfig/app-dev\/pkgconf/g' \
+    -e 's/x11-apps\/mkfontscale/xgui-live-app\/mkfontscale/g' \
+    -e 's/x11-misc\/shared-mime-info/xgui-live-app\/shared-mime-info/g' \
+    -e 's/\${EPREFIX}\$\(qt5_get_libdir\)\/qt5\/bin/\/usr\/bin/g' \
+    -e 's/\$(get_abi_LDFLAGS)/\${LDFLAGS}/g' \
+    -e 's/get_abi_CHOST/CHOST/g' \
+    -e 's/app-dev\/ninja/app-dev\/samurai/g'
 
-#insert on 3rd line
-sed -i '3i\PYTHON_COMPAT=( python3_10 python3_11 )\' /var/db/repos/bp/eclass/python-utils-r1.eclass
-
-sed -i 's/echo\ \/usr/echo\ /' /var/db/repos/bp/eclass/kernel-2.eclass
-echo\ \/usr
-echo\
+# Specific modifications to individual eclass files
+sed -i 's/.*qt5\/bin.*/	echo\ \/usr\/bin/' "${ECCLASS_DIR}/qmake-utils.eclass"
+sed -i 's/var\/lib/var/' "${ECCLASS_DIR}/meson.eclass"
+sed -i '3i\PYTHON_COMPAT=( python3_11 python3_12 python3_13 )\' /var/db/repos/bp/eclass/python-utils-r1.eclass
+sed -i 's/echo\ \/usr/echo\ /' "${ECCLASS_DIR}/kernel-2.eclass"
