improve package update scripts

diff --git a/app-core/ugscripts/files/sbin/upApp b/app-core/ugscripts/files/sbin/upApp
--- a/app-core/ugscripts/files/sbin/upApp
+++ b/app-core/ugscripts/files/sbin/upApp
@@ -97,6 +97,28 @@ update_vim_ebuild() {
     echo "Vim ebuild updated to version ${latest_version} in ${new_file_path}."
 }
 
+fetch_latest_cryptsetup_version() {
+    local base_url="https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/"
+    # Scrape the main page for the latest version directory
+    local latest_version=$(curl -s "$base_url" | grep -oP 'href="v[0-9]+\.[0-9]+/' | grep -v -- "-rc" | sort -Vr | head -1 | cut -d '"' -f 2)
+
+    if [[ -z "$latest_version" ]]; then
+        echo "Failed to fetch the latest Cryptsetup version directory"
+        return 1
+    fi
+
+    # Navigate to the latest version directory and get the version of the final release
+    local version_page="${base_url}${latest_version}"
+    local latest_final_version=$(curl -s "$version_page" | grep -oP 'cryptsetup-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | sort -Vr | head -1)
+
+    if [[ -z "$latest_final_version" ]]; then
+        echo "Failed to find the latest Cryptsetup final version"
+        return 1
+    fi
+
+    echo "$latest_final_version"
+}
+
 update_ebuild() {
     local PACKAGE_PATH="${REPO_PATH}/$1"
     local PACKAGE_NAME="$2"
@@ -148,3 +170,7 @@ curl_version=$(fetch_latest_curl_version)
 # Update Vim
 vim_version=$(fetch_latest_vim_version)
 [[ $? -eq 0 ]] && update_vim_ebuild "app-core/vim" "vim" "$vim_version"
+
+# Update Cryptsetup
+cryptsetup_version=$(fetch_latest_cryptsetup_version)
+[[ $? -eq 0 ]] && update_ebuild "app-fs/cryptsetup" "cryptsetup" "$cryptsetup_version"
