ugscripts-2.1

diff --git a/app-core/ugscripts/files/sbin/upApp b/app-core/ugscripts/files/sbin/upApp
--- a/app-core/ugscripts/files/sbin/upApp
+++ b/app-core/ugscripts/files/sbin/upApp
@@ -11,129 +11,137 @@ ERROR_LOG="${TMP_DIR}/${PROGNAME}-error.log"
 JSON_LOG="${TMP_DIR}/${PROGNAME}-json.log"
 
 mkdir -p "$TMP_DIR"
-	: > "$ERROR_LOG"
-	: > "$JSON_LOG"
-	: > "$DEBUG_LOG"
+: > "$ERROR_LOG"
+: > "$JSON_LOG"
+: > "$DEBUG_LOG"
 
 handle_github() {
-    local repo_url="$1"
-    local repo_slug=$(echo "$repo_url" | sed -E 's|https?://github\.com/([^/]+/[^/]+).*|\1|')
-    local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
+	local repo_url="$1"
+	local repo_slug=$(echo "$repo_url" | sed -E 's|https?://github\.com/([^/]+/[^/]+).*|\1|')
+	local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
 
-    echo "repo_slug $repo_slug" >> "$DEBUG_LOG"
-    echo "urlencode $encoded_slug" >> "$DEBUG_LOG"
+	echo "repo_slug $repo_slug" >> "$DEBUG_LOG"
+	echo "urlencode $encoded_slug" >> "$DEBUG_LOG"
 
-    local releases_api_url="https://api.github.com/repos/$repo_slug/releases/latest"
-    local tags_api_url="https://api.github.com/repos/$repo_slug/tags"
-    local auth_header="Authorization: token $GITHUB_TOKEN"
-    echo "auth_header $auth_header" >> "$DEBUG_LOG"
+	local releases_api_url="https://api.github.com/repos/$repo_slug/releases/latest"
+	local tags_api_url="https://api.github.com/repos/$repo_slug/tags"
+	local auth_header="Authorization: token $GITHUB_TOKEN"
+	echo "auth_header $auth_header" >> "$DEBUG_LOG"
 
-    local latest_release_info=$(curl -s -H "$auth_header" "$releases_api_url")
-    local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
-    echo "api_url $releases_api_url" >> "$DEBUG_LOG"
-    echo "latest_release_info $latest_release_info" >> "$JSON_LOG"
+	local latest_release_info=$(curl -s -H "$auth_header" "$releases_api_url")
+	local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
+	echo "api_url $releases_api_url" >> "$DEBUG_LOG"
+	echo "latest_release_info $latest_release_info" >> "$JSON_LOG"
 	echo "latest_version $latest_version" >> "$DEBUG_LOG"
 
-    if [[ -z "$latest_version" || "$latest_version" == "null" ]]; then
-        echo "No valid release found, checking tags..." >> "$DEBUG_LOG"
-        local latest_tag_info=$(curl -s -H "$auth_header" "$tags_api_url" | jq -r '.[0].name')
-        echo "api_url $tags_api_url" >> "$DEBUG_LOG"
-        echo "latest_tag_info $latest_tag_info" >> "$JSON_LOG"
+	if [[ -z "$latest_version" || "$latest_version" == "null" ]]; then
+		echo "No valid release found, checking tags..." >> "$DEBUG_LOG"
+		local latest_tag_info=$(curl -s -H "$auth_header" "$tags_api_url" | jq -r '.[0].name')
+		echo "api_url $tags_api_url" >> "$DEBUG_LOG"
+		echo "latest_tag_info $latest_tag_info" >> "$JSON_LOG"
 
-        if [[ -z "$latest_tag_info" || "$latest_tag_info" == "null" ]]; then
-            echo "Failed to fetch latest tag info" >> "$ERROR_LOG"
-            return 1
-        else
-            latest_version="$latest_tag_info"
-        fi
-    fi
+		if [[ -z "$latest_tag_info" || "$latest_tag_info" == "null" ]]; then
+			echo "Failed to fetch latest tag info" >> "$ERROR_LOG"
+			return 1
+		else
+			latest_version="$latest_tag_info"
+		fi
+	fi
 
-    latest_version="${latest_version#v}"
-    latest_version="${latest_version//_/\.}"
+	if [[ "$latest_version" == v* ]]; then
+		latest_version="${latest_version#v}"
+	fi
 
-    echo "Successfully fetched version info: $latest_version" >> "$DEBUG_LOG"
-    echo "$latest_version"
-    return 0
+	latest_version="${latest_version//_/\.}"
+	latest_version=$(echo "$latest_version" | sed -E "s/^.*-([0-9]+(\.[0-9]+)*).*/\1/")
+
+	echo "Successfully fetched version info: $latest_version" >> "$DEBUG_LOG"
+	echo "$latest_version"
+	return 0
 }
 
 handle_gitlab() {
-    local repo_url="$1"
-    local repo_slug=$(echo "$repo_url" | sed -E 's|https?://gitlab\.com/([^/]+/[^/]+).*|\1|')
-    local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
-    local api_url="https://gitlab.com/api/v4/projects/$encoded_slug/releases"
-    local auth_header="Authorization: Bearer $GITLAB_TOKEN"
-    local latest_release_info=$(curl -s -H "$auth_header" "$api_url" | jq '[.[] | select(.released_at)] | max_by(.released_at)')
-    if [[ $? -ne 0 || -z "$latest_release_info" ]]; then
-        echo "Failed to fetch latest release info"
-        return 1
-    else
-        local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
-        echo "$latest_version"
-    fi
+	local repo_url="$1"
+	local repo_slug=$(echo "$repo_url" | sed -E 's|https?://gitlab\.com/([^/]+/[^/]+).*|\1|')
+	local encoded_slug=$(echo "$repo_slug" | sed 's/\//%2F/g')
+	local api_url="https://gitlab.com/api/v4/projects/$encoded_slug/releases"
+	local auth_header="Authorization: Bearer $GITLAB_TOKEN"
+	local latest_release_info=$(curl -s -H "$auth_header" "$api_url" | jq '[.[] | select(.released_at)] | max_by(.released_at)')
+	if [[ $? -ne 0 || -z "$latest_release_info" ]]; then
+		echo "Failed to fetch latest release info"
+		return 1
+	else
+		local latest_version=$(echo "$latest_release_info" | jq -r '.tag_name')
+		echo "$latest_version"
+	fi
 }
 
 update_github_package() {
-    local category="$1"
-    local package_name="$2"
-    local repo_url="$3"
-    local latest_version=$(handle_github "$repo_url")
-    if [[ $? -eq 0 ]]; then
-        update_ebuild "${category}/${package_name}" "${package_name}" "${latest_version}"
-    else
-        echo "Failed to update $package_name package" >> "$ERROR_LOG"
-    fi
+	local category="$1"
+	local package_name="$2"
+	local repo_url="$3"
+	local latest_version=$(handle_github "$repo_url")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "${category}/${package_name}" "${package_name}" "${latest_version}"
+	else
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
+	fi
 }
 
 update_ebuild() {
-    local package_path="${REPO_PATH}/$1"
-    local package_name="$2"
-    local latest_version="$3"
+	local package_path="${REPO_PATH}/$1"
+	local package_name="$2"
+	local latest_version="$3"
 
-    local new_ebuild_filename="${package_name}-${latest_version}.ebuild"
-    local new_ebuild_file="${package_path}/${new_ebuild_filename}"
+	local new_ebuild_filename="${package_name}-${latest_version}.ebuild"
+	local new_ebuild_file="${package_path}/${new_ebuild_filename}"
 
-    local ebuild_file=$(find "${package_path}" -type f -name "${package_name}-[0-9]*.ebuild" | sort -V | tail -n 1)
+	echo "Updating ebuild for package_path: $package_path, package_name: $package_name, latest_version: $latest_version" >> "$DEBUG_LOG"
+	echo "New ebuild filename: $new_ebuild_filename" >> "$DEBUG_LOG"
+	echo "New ebuild file path: $new_ebuild_file" >> "$DEBUG_LOG"
 
-    local current_version=$(basename "$ebuild_file" | sed -e "s/^${package_name}-//" -e 's/\.ebuild$//')
+	local ebuild_file=$(find "${package_path}" -type f -name "${package_name}-[0-9]*.ebuild" | sort -V | tail -n 1)
+	echo "Found ebuild file: $ebuild_file" >> "$DEBUG_LOG"
 
-    echo "Current version: $current_version, Latest version: $latest_version"
+	if [[ -z "$ebuild_file" ]]; then
+		echo "No existing ebuild file found for ${package_name} at ${package_path}." >> "$ERROR_LOG"
+		return 1
+	fi
 
-    if [[ "$current_version" == "$latest_version" ]]; then
-        echo "No update needed for ${package_name} as it is already at the latest version: ${latest_version}."
-        return
-    fi
+	local current_version=$(basename "$ebuild_file" | sed -e "s/^${package_name}-//" -e 's/\.ebuild$//')
+	echo "Current version: $current_version" >> "$DEBUG_LOG"
 
-    if [[ -f "$new_ebuild_file" ]]; then
-        echo "Ebuild file ${new_ebuild_filename} already exists. No update needed."
-        return
-    fi
+	if [[ "$current_version" == "$latest_version" ]]; then
+		echo "No update needed for ${package_name} as it is already at the latest version: ${latest_version}." >> "$DEBUG_LOG"
+		return
+	fi
 
-    if [[ -z "$ebuild_file" ]]; then
-        echo "No existing ebuild file found for ${package_name} at ${package_path}."
-        return 1
-    fi
+	if [[ -f "$new_ebuild_file" ]]; then
+		echo "Ebuild file ${new_ebuild_filename} already exists. No update needed." >> "$DEBUG_LOG"
+		return
+	fi
 
-    mv "$ebuild_file" "$new_ebuild_file"
-    echo "New ebuild file created for ${package_name}: ${new_ebuild_filename}"
+	mv "$ebuild_file" "$new_ebuild_file"
+	echo "New ebuild file created for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
 
-    if finalize_update "$package_path" "$package_name" "$new_ebuild_filename" "$latest_version"; then
-        echo "Ebuild successfully updated for ${package_name}: ${new_ebuild_filename}"
-    else
-        echo "Failed to update ebuild for ${package_name}"
-        return 1
-    fi
+	if finalize_update "$package_path" "$package_name" "$new_ebuild_filename" "$latest_version"; then
+		echo "Ebuild successfully updated for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
+	else
+		echo "Failed to update ebuild for ${package_name}" >> "$ERROR_LOG"
+		return 1
+	fi
 }
 
 update_gitlab_package() {
-    local category="$1"
-    local package_name="$2"
-    local repo_url="$3"
-    local latest_version=$(handle_gitlab "$repo_url")
-    if [[ $? -eq 0 ]]; then
-        update_ebuild "${category}/${package_name}" "$package_name" "$latest_version"
-    else
-        echo "Failed to update $package_name package"
-    fi
+	local category="$1"
+	local package_name="$2"
+	local repo_url="$3"
+	local latest_version=$(handle_gitlab "$repo_url")
+	if [[ $? -eq 0 ]]; then
+		update_ebuild "${category}/${package_name}" "$package_name" "$latest_version"
+	else
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
+	fi
 }
 
 finalize_update() {
@@ -142,8 +150,10 @@ finalize_update() {
 	local new_ebuild_filename="$3"
 	local version="$4"
 
+	echo "Finalizing update for $package_name in $package_path" >> "$DEBUG_LOG"
+
 	if ! (cd "$package_path" && pkgdev manifest); then
-		echo "Error generating manifest for ${package_name}. Skipping..."
+		echo "Error generating manifest for ${package_name}. Skipping..." >> "$ERROR_LOG"
 		return 1
 	fi
 
@@ -156,7 +166,7 @@ finalize_update() {
 			commit -m "Update ${package_name} to ${version}" && \
 		git push origin HEAD)
 
-	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}"
+	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}" >> "$DEBUG_LOG"
 }
 
 fetch_latest_gnu_version() {
@@ -166,7 +176,7 @@ fetch_latest_gnu_version() {
 			sort -Vr | \
 		head -1)
 	if [[ -z "$latest_version" ]]; then
-		echo "Failed to fetch the latest $1 version"
+		echo "Failed to fetch the latest $1 version" >> "$ERROR_LOG"
 		return 1
 	fi
 	echo "$latest_version"
@@ -177,7 +187,7 @@ fetch_latest_cryptsetup_version() {
 	local latest_version=$(curl -s "$base_url" | grep -oP 'href="v[0-9]+\.[0-9]+/' | grep -v -- "-rc" | sort -Vr | head -1 | cut -d '"' -f 2)
 
 	if [[ -z "$latest_version" ]]; then
-		echo "Failed to fetch the latest Cryptsetup version directory"
+		echo "Failed to fetch the latest Cryptsetup version directory" >> "$ERROR_LOG"
 		return 1
 	fi
 
@@ -185,7 +195,7 @@ fetch_latest_cryptsetup_version() {
 	local latest_final_version=$(curl -s "$version_page" | grep -oP 'cryptsetup-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | sort -Vr | head -1)
 
 	if [[ -z "$latest_final_version" ]]; then
-		echo "Failed to find the latest Cryptsetup final version"
+		echo "Failed to find the latest Cryptsetup final version" >> "$ERROR_LOG"
 		return 1
 	fi
 
@@ -214,7 +224,7 @@ fetch_latest_git_version() {
 		head -1)
 
 	if [[ -z "$latest_version" ]]; then
-		echo "Failed to fetch the latest version from $repo_url"
+		echo "Failed to fetch the latest version from $repo_url" >> "$ERROR_LOG"
 		return 1
 	fi
 
@@ -231,7 +241,7 @@ update_git_package() {
 	if [[ $? -eq 0 ]]; then
 		update_ebuild "${category}/${package_name}" "$package_name" "$package_version"
 	else
-		echo "Failed to update $package_name package"
+		echo "Failed to update $package_name package" >> "$ERROR_LOG"
 	fi
 }
 
