improve updates

diff --git a/app-core/ugscripts/files/sbin/upApp b/app-core/ugscripts/files/sbin/upApp
--- a/app-core/ugscripts/files/sbin/upApp
+++ b/app-core/ugscripts/files/sbin/upApp
@@ -2,6 +2,29 @@
 
 REPO_PATH="/var/db/repos/bp"
 
+finalize_update() {
+	local package_path="$1"
+	local package_name="$2"
+	local new_ebuild_filename="$3"
+	local version="$4"
+
+	if ! (cd "$package_path" && pkgdev manifest); then
+		echo "Error generating manifest for ${package_name}. Skipping..."
+		return 1
+	fi
+
+	(cd "$package_path" && \
+			git add --all . && \
+			git -c user.name="${BOT_USER}" \
+			-c user.email="${BOT_EMAIL}" \
+			-c commit.gpgsign=true \
+			-c user.signingkey="${BOT_KEYID}" \
+			commit -m "Update ${package_name} to ${version}" && \
+		git push origin HEAD)
+
+	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}"
+}
+
 fetch_latest_boost_version() {
 	local boost_url="https://www.boost.org/users/history/"
 	local latest_version=$(curl -s "$boost_url" | grep -oP 'data-current-version="\K\d+\.\d+\.\d+')
@@ -15,9 +38,9 @@ fetch_latest_boost_version() {
 fetch_latest_curl_version() {
 	local curl_page_url="https://curl.se/download/"
 	local latest_version=$(curl -s "$curl_page_url" | \
-						   grep -oP '<td>\K\d+\.\d+\.\d+(?=</td>)' | \
-						   sort -Vr | \
-						   head -1)
+			grep -oP '<td>\K\d+\.\d+\.\d+(?=</td>)' | \
+			sort -Vr | \
+		head -1)
 	if [[ -z "$latest_version" ]]; then
 		echo "Failed to fetch the latest cURL version"
 		return 1
@@ -28,9 +51,9 @@ fetch_latest_curl_version() {
 fetch_latest_vim_version() {
 	local vim_git_url="https://github.com/vim/vim.git"
 	local latest_version=$(git ls-remote --tags --sort="-v:refname" "$vim_git_url" | \
-						grep -oP 'refs/tags/v\K\d+\.\d+\.\d+' | \
-						sort -urV | \
-						head -1)
+			grep -oP 'refs/tags/v\K\d+\.\d+\.\d+' | \
+			sort -urV | \
+		head -1)
 	if [[ -z "$latest_version" ]]; then
 		echo "Failed to fetch the latest Vim version"
 		return 1
@@ -41,9 +64,9 @@ fetch_latest_vim_version() {
 fetch_latest_gnu_version() {
 	local base_url="https://ftp.gnu.org/gnu/$1/"
 	local latest_version=$(curl -s "$base_url" | grep -oP 'href="\K'$1'-[0-9.]+(?=\.tar)' | \
-							sed 's/'$1'-//g' | \
-							sort -Vr | \
-							head -1)
+			sed 's/'$1'-//g' | \
+			sort -Vr | \
+		head -1)
 	if [[ -z "$latest_version" ]]; then
 		echo "Failed to fetch the latest $1 version"
 		return 1
@@ -53,7 +76,6 @@ fetch_latest_gnu_version() {
 
 fetch_latest_cryptsetup_version() {
 	local base_url="https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/"
-	# Scrape the main page for the latest version directory
 	local latest_version=$(curl -s "$base_url" | grep -oP 'href="v[0-9]+\.[0-9]+/' | grep -v -- "-rc" | sort -Vr | head -1 | cut -d '"' -f 2)
 
 	if [[ -z "$latest_version" ]]; then
@@ -61,7 +83,6 @@ fetch_latest_cryptsetup_version() {
 		return 1
 	fi
 
-	# Navigate to the latest version directory and get the version of the final release
 	local version_page="${base_url}${latest_version}"
 	local latest_final_version=$(curl -s "$version_page" | grep -oP 'cryptsetup-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | sort -Vr | head -1)
 
@@ -107,37 +128,21 @@ update_vim_ebuild() {
 		return 1
 	fi
 
-	# Ensure the version is formatted correctly (no leading 'v')
 	latest_version=${latest_version#v}
 
-	# Construct the new filename with the full version number
 	local new_ebuild_filename="${PACKAGE_NAME}-${latest_version}.ebuild"
 	local new_file_path="${PACKAGE_PATH}/${new_ebuild_filename}"
 
-	# Rename the ebuild file to match the latest version, if it doesn't already exist
 	if [[ "$vim_ebuild_file" != "$new_file_path" ]]; then
 		mv "$vim_ebuild_file" "$new_file_path"
 		echo "Renamed Vim ebuild to $new_ebuild_filename."
+		(cd "${PACKAGE_PATH}" && pkgdev manifest)
+		finalize_update "$PACKAGE_PATH" "$PACKAGE_NAME" "$new_ebuild_filename" "$latest_version"
+		echo "Vim ebuild updated to version ${latest_version} in ${new_file_path}."
 	else
 		echo "Vim ebuild is already up to date with version $latest_version."
 		return 0
 	fi
-
-	(cd ${REPO_PATH} && pkgdev manifest)
-	(cd "$REPO_PATH" && \
-	git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			add . && \
-		git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			commit -m "Update Vim to ${latest_version}" && \
-		git push)
-	(cd ${REPO_PATH} && git add . && git commit -m "Update Vim to ${latest_version}")
-	echo "Vim ebuild updated to version ${latest_version} in ${new_file_path}."
 }
 
 update_gnu_package() {
@@ -149,18 +154,17 @@ update_gnu_package() {
 }
 
 fetch_latest_git_version() {
-	local repo_url="$1" # GitHub repository URL
-	local include_v_prefix="$2" # Whether the tags include a 'v' prefix ('true' or 'false')
+	local repo_url="$1"
+	local include_v_prefix="$2"
 
-	# Adjust the grep pattern based on whether the version tags include a 'v' prefix
 	local version_pattern='refs/tags/\K[0-9.]+(?=\^{})'
 	if [[ "$include_v_prefix" == "true" ]]; then
 		version_pattern='refs/tags/v\K[0-9.]+(?=\^{})'
 	fi
 
 	local latest_version=$(git ls-remote --tags --sort="-v:refname" "$repo_url" | \
-							grep -oP "$version_pattern" | \
-							head -1)
+			grep -oP "$version_pattern" | \
+		head -1)
 
 	if [[ -z "$latest_version" ]]; then
 		echo "Failed to fetch the latest version from $repo_url"
@@ -178,7 +182,6 @@ update_git_package() {
 
 	local package_version=$(fetch_latest_git_version "$repo_url" "$include_v_prefix")
 	if [[ $? -eq 0 ]]; then
-		# Now using the dynamic category provided as the argument
 		update_ebuild "${category}/${package_name}" "$package_name" "$package_version"
 	else
 		echo "Failed to update $package_name package"
@@ -206,19 +209,7 @@ update_ebuild() {
 		fi
 
 		mv "$ebuild_file" "$new_ebuild_file"
-		(cd ${REPO_PATH} && pkgdev manifest)
-		(cd "$REPO_PATH" && \
-		git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			add . && \
-		git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			commit -m "Update ${PACKAGE_NAME} to ${version}" && \
-		git push)
+		finalize_update "$PACKAGE_PATH" "$PACKAGE_NAME" "$new_ebuild_filename" "$version"
 
 		echo "Ebuild updated for ${PACKAGE_NAME}: ${new_ebuild_filename}"
 		break
@@ -230,33 +221,26 @@ update_ebuild() {
 	fi
 }
 
-# Update Boost
 boost_version=$(fetch_latest_boost_version)
 [[ $? -eq 0 ]] && update_ebuild "lib-dev/boost" "boost" "$boost_version"
 
-# Update Boost Build
 [[ $? -eq 0 ]] && update_ebuild "lib-dev/boost-build" "boost-build" "$boost_version"
 
-# Update cURL
 curl_version=$(fetch_latest_curl_version)
 [[ $? -eq 0 ]] && update_ebuild "app-net/curl" "curl" "$curl_version"
 
-# Update Vim
 vim_version=$(fetch_latest_vim_version)
 [[ $? -eq 0 ]] && update_vim_ebuild "app-core/vim" "vim" "$vim_version"
 
-# Update Cryptsetup
 cryptsetup_version=$(fetch_latest_cryptsetup_version)
 [[ $? -eq 0 ]] && update_ebuild "app-fs/cryptsetup" "cryptsetup" "$cryptsetup_version"
 
-# Update ncurses
 ncurses_version=$(fetch_latest_ncurses_version)
 if [[ $? -eq 0 ]]; then
 	update_ebuild "lib-core/ncurses" "ncurses" "$ncurses_version"
 	update_ebuild "lib-core/ncurses5-compat" "ncurses5-compat" "$ncurses_version"
 fi
 
-# Update GNU stuff
 if [[ $? -eq 0 ]]; then
 	update_gnu_package "autoconf-archive"
 	update_gnu_package "autoconf"
@@ -268,5 +252,5 @@ if [[ $? -eq 0 ]]; then
 	update_gnu_package "texinfo"
 fi
 
-update_git_package "app-build" "bc" "https://github.com/gavinhoward/bc.git" "false"
+update_git_package "app-util" "bc" "https://github.com/gavinhoward/bc.git" "false"
 update_git_package "app-net" "bluez" "https://git.kernel.org/pub/scm/bluetooth/bluez.git" "false"
diff --git a/app-core/ugscripts/files/sbin/upBrowsers b/app-core/ugscripts/files/sbin/upBrowsers
--- a/app-core/ugscripts/files/sbin/upBrowsers
+++ b/app-core/ugscripts/files/sbin/upBrowsers
@@ -2,44 +2,63 @@
 
 REPO_PATH="/var/db/repos/bp"
 
+finalize_update() {
+	local package_path="$1"
+	local package_name="$2"
+	local new_ebuild_filename="$3"
+	local version="$4"
+
+	if ! (cd "$package_path" && pkgdev manifest); then
+		echo "Error generating manifest for ${package_name}. Skipping..."
+		return 1
+	fi
+
+	(cd "$package_path" && \
+			git add --all . && \
+			git -c user.name="${BOT_USER}" \
+			-c user.email="${BOT_EMAIL}" \
+			-c commit.gpgsign=true \
+			-c user.signingkey="${BOT_KEYID}" \
+			commit -m "Update ${package_name} to ${version}" && \
+		git push origin HEAD)
+
+	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}"
+}
+
 fetch_latest_brave_versions() {
 	local github_repo_url="https://github.com/brave/brave-browser.git"
 	local max_versions_to_check=10
 	local fetched_versions=()
 
-	# Fetch the tags and sort them in descending order based on version numbers
 	local latest_tags=$(git ls-remote --tags --sort="-v:refname" $github_repo_url | \
-						grep -oP 'refs/tags/v\d+\.\d+\.\d+' | \
-						sed 's/refs\/tags\/v//' | \
-						sort -rV | \
-						head -"$max_versions_to_check")
+			grep -oP 'refs/tags/v\d+\.\d+\.\d+' | \
+			sed 's/refs\/tags\/v//' | \
+			sort -rV | \
+		head -"$max_versions_to_check")
 
 	if [[ -z "$latest_tags" ]]; then
 		echo "Failed to fetch the latest Brave Browser versions"
 		return 1
 	fi
 
-	# Iterate over tags and check for available downloads
 	IFS=$'\n' read -rd '' -a versions <<< "$latest_tags"
 	for version in "${versions[@]}"; do
 		local download_url="https://github.com/brave/brave-browser/releases/download/v${version}/brave-browser-nightly_${version}_amd64.deb"
 
 		if curl --output /dev/null --silent --head --fail "$download_url"; then
 			fetched_versions+=("$version")
-			# Break the loop if we have found enough versions
+
 			if [[ ${#fetched_versions[@]} -eq $max_versions_to_check ]]; then
 				break
 			fi
 		fi
 	done
 
-	# Check if we found any valid versions
 	if [[ ${#fetched_versions[@]} -eq 0 ]]; then
 		echo "No valid Brave versions found"
 		return 1
 	fi
 
-	# Return the valid versions
 	printf '%s\n' "${fetched_versions[@]}"
 }
 
@@ -74,10 +93,6 @@ fetch_latest_firefox_version() {
 	return 1
 }
 
-version_gt() {
-	test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
-}
-
 update_ebuild() {
 	local PACKAGE_PATH="${REPO_PATH}/$1"
 	local PACKAGE_NAME="$2"
@@ -88,42 +103,29 @@ update_ebuild() {
 		local new_ebuild_filename="${PACKAGE_NAME}-${version}.ebuild"
 		local new_ebuild_file="${PACKAGE_PATH}/${new_ebuild_filename}"
 
-		# Find the most recent existing ebuild file
 		local existing_ebuild_file=$(find "${PACKAGE_PATH}" -maxdepth 1 -type f -name "${PACKAGE_NAME}-*.ebuild" | sort | tail -n 1)
 		if [[ -z "$existing_ebuild_file" ]]; then
 			echo "No ebuild file found for ${PACKAGE_NAME}."
 			continue
 		fi
 
-		# Extract version from the existing ebuild filename
 		local existing_version=$(basename "$existing_ebuild_file" | grep -oP "${PACKAGE_NAME}-\K[\d\.]+(?=.ebuild)")
 
-		# Compare versions using the version_gt function
 		if ! version_gt "$version" "$existing_version"; then
 			echo "Skipping ${version}, as it's not newer than the existing version ${existing_version}."
-			return 0
+			continue
 		fi
 
 		if [[ -f "$new_ebuild_file" ]]; then
 			echo "Ebuild file ${new_ebuild_filename} already exists."
-			return 0
+			continue
 		fi
 
 		mv "$existing_ebuild_file" "$new_ebuild_file"
-		(cd ${REPO_PATH} && pkgdev manifest)
-		(cd "$REPO_PATH" && \
-		git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			add . && \
-		git -c user.name="1g4-bot" \
-			-c user.email="share@1g4.org" \
-			-c commit.gpgsign=true \
-			-c user.signingkey=AFFCE613154C05AA \
-			commit -m "Update ${PACKAGE_NAME} to ${version}" && \
-		git push)
+		echo "Ebuild file renamed to ${new_ebuild_filename}."
 
+		(cd "${PACKAGE_PATH}" && pkgdev manifest) || continue
+		finalize_update "$PACKAGE_PATH" "$PACKAGE_NAME" "$new_ebuild_filename" "$version"
 		echo "Ebuild updated for ${PACKAGE_NAME}: ${new_ebuild_filename}"
 		break
 	done
@@ -134,14 +136,15 @@ update_ebuild() {
 	fi
 }
 
-# Update Brave
+version_gt() {
+	test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
+}
+
 brave_versions=$(fetch_latest_brave_versions)
 [[ $? -eq 0 ]] && update_ebuild "bin/brave-nightly-bin" "brave-nightly-bin" "$brave_versions"
 
-# Update Chrome
 chrome_version=$(fetch_latest_chrome_version)
 [[ $? -eq 0 ]] && update_ebuild "bin/google-chrome-unstable" "google-chrome-unstable" "$chrome_version"
 
-# Update Firefox
 firefox_version=$(fetch_latest_firefox_version)
 [[ $? -eq 0 ]] && update_ebuild "bin/firefox-nightly-bin" "firefox-nightly-bin" "$firefox_version"
